<?php /** @var $block \Magento\Catalog\Block\Product\View */ ?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
            <div class="control">
                <span class="minus"><button class="action secondary" type="button" title="<?= __('Reduce the quantity') ?>">-</button></span>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                       title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <span class="plus"><button class="action secondary" type="button" title="<?= __('Increase the quantity'); ?>" />+</button></span>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<script type="text/javascript">
    require(['jquery'], function ($) {
        $('.box-tocart .minus').on('click', function () {
            var qty = parseInt($('#qty').val()) - 1;
            $('#qty').val(qty).trigger('change');
        });
        $('.box-tocart .plus').on('click', function () {
            var qty = parseInt($('#qty').val()) + 1;
            $('#qty').val(qty).trigger('change');
        });
        $('#qty').on('change', function () {
            var qty = parseInt($(this).val());
            if (qty < 1) {
                $(this).val(0);
            }
        });
    });
</script>
